### ISSUE TITLE
关于AbilityPageAdapter填充Ability的一些问题

### ISSUE THREAD

**Issue by Fomovet** [taoweiji/single-activity-navigation#1]
使用AbilityPageAdapter填充的所有Abililty对象中，获取到的NavController对象为空
比如在Abililty对象中使用 findNavController().navigate(new TestResultAbility());跳转将会提示NavController对象为空

**Comment by taoweiji** [comment]
好的，我改进一下

**Comment by taoweiji** [comment]
你也可以通过获取容器的Ability

**Comment by taoweiji** [comment]
0.1.8 版本已经改进这个问题，非常感谢你的反馈
